export TESTING_USER=${TESTING_USER:-floatvec_test}
export TESTING_PASSWORD=${TESTING_PASSWORD:-floatvec_test}
export TESTING_DATABASE=${TESTING_DATABASE:-floatvec_test}
export TESTING_HOST=${TESTING_HOST:-localhost}
export TESTING_PORT=${TESTING_PORT:-5432}

